"""This module contains the pydantic schemas for the database models."""

from pydantic import BaseModel

# Book schema
# for a new book to be added
# the book_name and author fields are required
# no id field since it will be generated by the database


class Book(BaseModel):
    book_name: str
    author: str

# BookWithId schema
# for a book that already exists
# the id field is required


class BookWithId(BaseModel):
    id: int
    book_name: str
    author: str
